version: '3.1'
services:
  shell:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/opt/tklinkchecker
    restart: always
    networks:
      - tklc
networks:
  tklc:
